/*
 * harena
 * harena
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.harena.api.endpoint.rest.api;

import com.harena.api.endpoint.rest.client.ApiClient;
import com.harena.api.endpoint.rest.client.ApiException;
import com.harena.api.endpoint.rest.client.ApiResponse;
import com.harena.api.endpoint.rest.client.Pair;

import com.harena.api.endpoint.rest.model.BadRequestException;
import com.harena.api.endpoint.rest.model.GetPatrimoines200Response;
import com.harena.api.endpoint.rest.model.InternalServerException;
import com.harena.api.endpoint.rest.model.Patrimoine;
import com.harena.api.endpoint.rest.model.ResourceNotFoundException;
import com.harena.api.endpoint.rest.model.TooManyRequestsException;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-29T12:58:40.550938700+01:00[GMT+01:00]", comments = "Generator version: 7.7.0")
public class PatrimoineApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public PatrimoineApi() {
    this(new ApiClient());
  }

  public PatrimoineApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * met à jour les patrimoines si le nom est donné, sinon on le crée
   * 
   * @param getPatrimoines200Response  (optional)
   * @return GetPatrimoines200Response
   * @throws ApiException if fails to make API call
   */
  public GetPatrimoines200Response crupdatePatrimoines(GetPatrimoines200Response getPatrimoines200Response) throws ApiException {
    ApiResponse<GetPatrimoines200Response> localVarResponse = crupdatePatrimoinesWithHttpInfo(getPatrimoines200Response);
    return localVarResponse.getData();
  }

  /**
   * met à jour les patrimoines si le nom est donné, sinon on le crée
   * 
   * @param getPatrimoines200Response  (optional)
   * @return ApiResponse&lt;GetPatrimoines200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetPatrimoines200Response> crupdatePatrimoinesWithHttpInfo(GetPatrimoines200Response getPatrimoines200Response) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = crupdatePatrimoinesRequestBuilder(getPatrimoines200Response);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("crupdatePatrimoines", localVarResponse);
        }
        return new ApiResponse<GetPatrimoines200Response>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<GetPatrimoines200Response>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder crupdatePatrimoinesRequestBuilder(GetPatrimoines200Response getPatrimoines200Response) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/patrimoines";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(getPatrimoines200Response);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * obtenir le patrimoine demandé
   * 
   * @param nomPatrimoine nom du patrimoine avec les espaces remplacés par \&quot;_\&quot; s&#39;il y en a (required)
   * @return Patrimoine
   * @throws ApiException if fails to make API call
   */
  public Patrimoine getPatrimoineByNom(String nomPatrimoine) throws ApiException {
    ApiResponse<Patrimoine> localVarResponse = getPatrimoineByNomWithHttpInfo(nomPatrimoine);
    return localVarResponse.getData();
  }

  /**
   * obtenir le patrimoine demandé
   * 
   * @param nomPatrimoine nom du patrimoine avec les espaces remplacés par \&quot;_\&quot; s&#39;il y en a (required)
   * @return ApiResponse&lt;Patrimoine&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Patrimoine> getPatrimoineByNomWithHttpInfo(String nomPatrimoine) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getPatrimoineByNomRequestBuilder(nomPatrimoine);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getPatrimoineByNom", localVarResponse);
        }
        return new ApiResponse<Patrimoine>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<Patrimoine>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getPatrimoineByNomRequestBuilder(String nomPatrimoine) throws ApiException {
    // verify the required parameter 'nomPatrimoine' is set
    if (nomPatrimoine == null) {
      throw new ApiException(400, "Missing the required parameter 'nomPatrimoine' when calling getPatrimoineByNom");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/patrimoines/{nom_patrimoine}"
        .replace("{nom_patrimoine}", ApiClient.urlEncode(nomPatrimoine.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * obtenir une liste paginée des patrimoines
   * 
   * @param page  (optional)
   * @param pageSize  (optional)
   * @return GetPatrimoines200Response
   * @throws ApiException if fails to make API call
   */
  public GetPatrimoines200Response getPatrimoines(Integer page, Integer pageSize) throws ApiException {
    ApiResponse<GetPatrimoines200Response> localVarResponse = getPatrimoinesWithHttpInfo(page, pageSize);
    return localVarResponse.getData();
  }

  /**
   * obtenir une liste paginée des patrimoines
   * 
   * @param page  (optional)
   * @param pageSize  (optional)
   * @return ApiResponse&lt;GetPatrimoines200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetPatrimoines200Response> getPatrimoinesWithHttpInfo(Integer page, Integer pageSize) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getPatrimoinesRequestBuilder(page, pageSize);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getPatrimoines", localVarResponse);
        }
        return new ApiResponse<GetPatrimoines200Response>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<GetPatrimoines200Response>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getPatrimoinesRequestBuilder(Integer page, Integer pageSize) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/patrimoines";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "page";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page", page));
    localVarQueryParameterBaseName = "page_size";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page_size", pageSize));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
