/*
 * harena
 * harena
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.harena.api.endpoint.rest.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.harena.api.endpoint.rest.model.Argent;
import com.harena.api.endpoint.rest.model.Devise;
import java.util.Arrays;
import java.util.Date;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FluxArgent
 */
class FluxArgentTest {
    private final FluxArgent model = new FluxArgent();

    /**
     * Model tests for FluxArgent
     */
    @Test
    void testFluxArgent() {
        // TODO: test FluxArgent
    }

    /**
     * Test the property 't'
     */
    @Test
    void tTest() {
        // TODO: test t
    }

    /**
     * Test the property 'nom'
     */
    @Test
    void nomTest() {
        // TODO: test nom
    }

    /**
     * Test the property 'valeurComptable'
     */
    @Test
    void valeurComptableTest() {
        // TODO: test valeurComptable
    }

    /**
     * Test the property 'devise'
     */
    @Test
    void deviseTest() {
        // TODO: test devise
    }

    /**
     * Test the property 'argent'
     */
    @Test
    void argentTest() {
        // TODO: test argent
    }

    /**
     * Test the property 'debut'
     */
    @Test
    void debutTest() {
        // TODO: test debut
    }

    /**
     * Test the property 'fin'
     */
    @Test
    void finTest() {
        // TODO: test fin
    }

    /**
     * Test the property 'fluxMensuel'
     */
    @Test
    void fluxMensuelTest() {
        // TODO: test fluxMensuel
    }

    /**
     * Test the property 'dateDOperation'
     */
    @Test
    void dateDOperationTest() {
        // TODO: test dateDOperation
    }

}
