/*
 * harena
 * harena
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.harena.api.endpoint.rest.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.harena.api.endpoint.rest.model.FluxArgent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FluxImpossibles
 */
class FluxImpossiblesTest {
    private final FluxImpossibles model = new FluxImpossibles();

    /**
     * Model tests for FluxImpossibles
     */
    @Test
    void testFluxImpossibles() {
        // TODO: test FluxImpossibles
    }

    /**
     * Test the property 'nomArgent'
     */
    @Test
    void nomArgentTest() {
        // TODO: test nomArgent
    }

    /**
     * Test the property 'date'
     */
    @Test
    void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'valeurArgent'
     */
    @Test
    void valeurArgentTest() {
        // TODO: test valeurArgent
    }

    /**
     * Test the property 'fluxArgents'
     */
    @Test
    void fluxArgentsTest() {
        // TODO: test fluxArgents
    }

}
