/*
 * harena
 * harena
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.harena.api.endpoint.rest.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.harena.api.endpoint.rest.model.Personne;
import java.util.Arrays;
import java.util.Date;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Patrimoine
 */
class PatrimoineTest {
    private final Patrimoine model = new Patrimoine();

    /**
     * Model tests for Patrimoine
     */
    @Test
    void testPatrimoine() {
        // TODO: test Patrimoine
    }

    /**
     * Test the property 'nom'
     */
    @Test
    void nomTest() {
        // TODO: test nom
    }

    /**
     * Test the property 'possesseur'
     */
    @Test
    void possesseurTest() {
        // TODO: test possesseur
    }

    /**
     * Test the property 't'
     */
    @Test
    void tTest() {
        // TODO: test t
    }

    /**
     * Test the property 'valeurComptable'
     */
    @Test
    void valeurComptableTest() {
        // TODO: test valeurComptable
    }

}
