/*
 * harena
 * harena
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.harena.api.endpoint.rest.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.harena.api.endpoint.rest.model.Argent;
import com.harena.api.endpoint.rest.model.FluxArgent;
import com.harena.api.endpoint.rest.model.Materiel;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PossessionAvecType
 */
class PossessionAvecTypeTest {
    private final PossessionAvecType model = new PossessionAvecType();

    /**
     * Model tests for PossessionAvecType
     */
    @Test
    void testPossessionAvecType() {
        // TODO: test PossessionAvecType
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'argent'
     */
    @Test
    void argentTest() {
        // TODO: test argent
    }

    /**
     * Test the property 'materiel'
     */
    @Test
    void materielTest() {
        // TODO: test materiel
    }

    /**
     * Test the property 'fluxArgent'
     */
    @Test
    void fluxArgentTest() {
        // TODO: test fluxArgent
    }

}
