/*
 * harena
 * harena
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.harena.api.endpoint.rest.api;

import com.harena.api.endpoint.rest.client.ApiException;
import com.harena.api.endpoint.rest.model.BadRequestException;
import com.harena.api.endpoint.rest.model.GetPatrimoines200Response;
import com.harena.api.endpoint.rest.model.InternalServerException;
import com.harena.api.endpoint.rest.model.Patrimoine;
import com.harena.api.endpoint.rest.model.ResourceNotFoundException;
import com.harena.api.endpoint.rest.model.TooManyRequestsException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for PatrimoineApi
 */
@Disabled
public class PatrimoineApiTest {

    private final PatrimoineApi api = new PatrimoineApi();

    
    /**
     * met à jour les patrimoines si le nom est donné, sinon on le crée
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void crupdatePatrimoinesTest() throws ApiException {
        GetPatrimoines200Response getPatrimoines200Response = null;
        GetPatrimoines200Response response = 
        api.crupdatePatrimoines(getPatrimoines200Response);
        
        // TODO: test validations
    }
    
    /**
     * obtenir le patrimoine demandé
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPatrimoineByNomTest() throws ApiException {
        String nomPatrimoine = null;
        Patrimoine response = 
        api.getPatrimoineByNom(nomPatrimoine);
        
        // TODO: test validations
    }
    
    /**
     * obtenir une liste paginée des patrimoines
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPatrimoinesTest() throws ApiException {
        Integer page = null;
        Integer pageSize = null;
        GetPatrimoines200Response response = 
        api.getPatrimoines(page, pageSize);
        
        // TODO: test validations
    }
    
}
