/*
 * harena
 * harena
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.harena.api.endpoint.rest.api;

import com.harena.api.endpoint.rest.client.ApiException;
import com.harena.api.endpoint.rest.model.BadRequestException;
import java.util.Date;
import com.harena.api.endpoint.rest.model.GetPatrimoineFluxImpossibles200Response;
import com.harena.api.endpoint.rest.model.InternalServerException;
import com.harena.api.endpoint.rest.model.ResourceNotFoundException;
import com.harena.api.endpoint.rest.model.TooManyRequestsException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for ProjectionFutureApi
 */
@Disabled
public class ProjectionFutureApiTest {

    private final ProjectionFutureApi api = new ProjectionFutureApi();

    
    /**
     * obtenir une liste des flux impossibles du patrimoine dans une intervalle donnée
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPatrimoineFluxImpossiblesTest() throws ApiException {
        String nomPatrimoine = null;
        java.time.LocalDate debut = null;
        java.time.LocalDate fin = null;
        GetPatrimoineFluxImpossibles200Response response = 
        api.getPatrimoineFluxImpossibles(nomPatrimoine, debut, fin);
        
        // TODO: test validations
    }
    
    /**
     * obtenir le graphe de projection d&#39;un patrimoine sur une plage de date donnée
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPatrimoineGraphTest() throws ApiException {
        String nomPatrimoine = null;
        java.time.LocalDate debut = null;
        java.time.LocalDate fin = null;
        byte[] response = 
        api.getPatrimoineGraph(nomPatrimoine, debut, fin);
        
        // TODO: test validations
    }
    
}
