/*
 * harena
 * harena
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.harena.api.endpoint.rest.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.harena.api.endpoint.rest.model.Argent;
import com.harena.api.endpoint.rest.model.Devise;
import java.util.Arrays;
import java.util.Date;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.harena.api.endpoint.rest.client.ApiClient;
/**
 * FluxArgent
 */
@JsonPropertyOrder({
  FluxArgent.JSON_PROPERTY_T,
  FluxArgent.JSON_PROPERTY_NOM,
  FluxArgent.JSON_PROPERTY_VALEUR_COMPTABLE,
  FluxArgent.JSON_PROPERTY_DEVISE,
  FluxArgent.JSON_PROPERTY_ARGENT,
  FluxArgent.JSON_PROPERTY_DEBUT,
  FluxArgent.JSON_PROPERTY_FIN,
  FluxArgent.JSON_PROPERTY_FLUX_MENSUEL,
  FluxArgent.JSON_PROPERTY_DATE_D_OPERATION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-29T12:58:40.550938700+01:00[GMT+01:00]", comments = "Generator version: 7.7.0")
public class FluxArgent implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_T = "t";
  private java.time.LocalDate t;

  public static final String JSON_PROPERTY_NOM = "nom";
  private String nom;

  public static final String JSON_PROPERTY_VALEUR_COMPTABLE = "valeur_comptable";
  private Integer valeurComptable;

  public static final String JSON_PROPERTY_DEVISE = "devise";
  private Devise devise;

  public static final String JSON_PROPERTY_ARGENT = "argent";
  private Argent argent;

  public static final String JSON_PROPERTY_DEBUT = "debut";
  private java.time.LocalDate debut;

  public static final String JSON_PROPERTY_FIN = "fin";
  private java.time.LocalDate fin;

  public static final String JSON_PROPERTY_FLUX_MENSUEL = "flux_mensuel";
  private Integer fluxMensuel;

  public static final String JSON_PROPERTY_DATE_D_OPERATION = "date_d_operation";
  private Integer dateDOperation;

  public FluxArgent() { 
  }

  public FluxArgent t(java.time.LocalDate t) {
    this.t = t;
    return this;
  }

  /**
   * Get t
   * @return t
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_T)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public java.time.LocalDate getT() {
    return t;
  }


  @JsonProperty(JSON_PROPERTY_T)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setT(java.time.LocalDate t) {
    this.t = t;
  }


  public FluxArgent nom(String nom) {
    this.nom = nom;
    return this;
  }

  /**
   * Get nom
   * @return nom
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getNom() {
    return nom;
  }


  @JsonProperty(JSON_PROPERTY_NOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNom(String nom) {
    this.nom = nom;
  }


  public FluxArgent valeurComptable(Integer valeurComptable) {
    this.valeurComptable = valeurComptable;
    return this;
  }

  /**
   * Get valeurComptable
   * @return valeurComptable
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALEUR_COMPTABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getValeurComptable() {
    return valeurComptable;
  }


  @JsonProperty(JSON_PROPERTY_VALEUR_COMPTABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValeurComptable(Integer valeurComptable) {
    this.valeurComptable = valeurComptable;
  }


  public FluxArgent devise(Devise devise) {
    this.devise = devise;
    return this;
  }

  /**
   * Get devise
   * @return devise
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEVISE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Devise getDevise() {
    return devise;
  }


  @JsonProperty(JSON_PROPERTY_DEVISE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDevise(Devise devise) {
    this.devise = devise;
  }


  public FluxArgent argent(Argent argent) {
    this.argent = argent;
    return this;
  }

  /**
   * Get argent
   * @return argent
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ARGENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Argent getArgent() {
    return argent;
  }


  @JsonProperty(JSON_PROPERTY_ARGENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArgent(Argent argent) {
    this.argent = argent;
  }


  public FluxArgent debut(java.time.LocalDate debut) {
    this.debut = debut;
    return this;
  }

  /**
   * Get debut
   * @return debut
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEBUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public java.time.LocalDate getDebut() {
    return debut;
  }


  @JsonProperty(JSON_PROPERTY_DEBUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDebut(java.time.LocalDate debut) {
    this.debut = debut;
  }


  public FluxArgent fin(java.time.LocalDate fin) {
    this.fin = fin;
    return this;
  }

  /**
   * Get fin
   * @return fin
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public java.time.LocalDate getFin() {
    return fin;
  }


  @JsonProperty(JSON_PROPERTY_FIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFin(java.time.LocalDate fin) {
    this.fin = fin;
  }


  public FluxArgent fluxMensuel(Integer fluxMensuel) {
    this.fluxMensuel = fluxMensuel;
    return this;
  }

  /**
   * Get fluxMensuel
   * @return fluxMensuel
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FLUX_MENSUEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getFluxMensuel() {
    return fluxMensuel;
  }


  @JsonProperty(JSON_PROPERTY_FLUX_MENSUEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFluxMensuel(Integer fluxMensuel) {
    this.fluxMensuel = fluxMensuel;
  }


  public FluxArgent dateDOperation(Integer dateDOperation) {
    this.dateDOperation = dateDOperation;
    return this;
  }

  /**
   * Get dateDOperation
   * @return dateDOperation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE_D_OPERATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getDateDOperation() {
    return dateDOperation;
  }


  @JsonProperty(JSON_PROPERTY_DATE_D_OPERATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateDOperation(Integer dateDOperation) {
    this.dateDOperation = dateDOperation;
  }


  /**
   * Return true if this FluxArgent object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FluxArgent fluxArgent = (FluxArgent) o;
    return Objects.equals(this.t, fluxArgent.t) &&
        Objects.equals(this.nom, fluxArgent.nom) &&
        Objects.equals(this.valeurComptable, fluxArgent.valeurComptable) &&
        Objects.equals(this.devise, fluxArgent.devise) &&
        Objects.equals(this.argent, fluxArgent.argent) &&
        Objects.equals(this.debut, fluxArgent.debut) &&
        Objects.equals(this.fin, fluxArgent.fin) &&
        Objects.equals(this.fluxMensuel, fluxArgent.fluxMensuel) &&
        Objects.equals(this.dateDOperation, fluxArgent.dateDOperation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(t, nom, valeurComptable, devise, argent, debut, fin, fluxMensuel, dateDOperation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FluxArgent {\n");
    sb.append("    t: ").append(toIndentedString(t)).append("\n");
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("    valeurComptable: ").append(toIndentedString(valeurComptable)).append("\n");
    sb.append("    devise: ").append(toIndentedString(devise)).append("\n");
    sb.append("    argent: ").append(toIndentedString(argent)).append("\n");
    sb.append("    debut: ").append(toIndentedString(debut)).append("\n");
    sb.append("    fin: ").append(toIndentedString(fin)).append("\n");
    sb.append("    fluxMensuel: ").append(toIndentedString(fluxMensuel)).append("\n");
    sb.append("    dateDOperation: ").append(toIndentedString(dateDOperation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `t` to the URL query string
    if (getT() != null) {
      joiner.add(String.format("%st%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getT()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `nom` to the URL query string
    if (getNom() != null) {
      joiner.add(String.format("%snom%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getNom()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `valeur_comptable` to the URL query string
    if (getValeurComptable() != null) {
      joiner.add(String.format("%svaleur_comptable%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getValeurComptable()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `devise` to the URL query string
    if (getDevise() != null) {
      joiner.add(getDevise().toUrlQueryString(prefix + "devise" + suffix));
    }

    // add `argent` to the URL query string
    if (getArgent() != null) {
      joiner.add(getArgent().toUrlQueryString(prefix + "argent" + suffix));
    }

    // add `debut` to the URL query string
    if (getDebut() != null) {
      joiner.add(String.format("%sdebut%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDebut()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `fin` to the URL query string
    if (getFin() != null) {
      joiner.add(String.format("%sfin%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getFin()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `flux_mensuel` to the URL query string
    if (getFluxMensuel() != null) {
      joiner.add(String.format("%sflux_mensuel%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getFluxMensuel()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `date_d_operation` to the URL query string
    if (getDateDOperation() != null) {
      joiner.add(String.format("%sdate_d_operation%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDateDOperation()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

