/*
 * harena
 * harena
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.harena.api.endpoint.rest.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.harena.api.endpoint.rest.model.Devise;
import java.util.Arrays;
import java.util.Date;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.harena.api.endpoint.rest.client.ApiClient;
/**
 * Materiel
 */
@JsonPropertyOrder({
  Materiel.JSON_PROPERTY_T,
  Materiel.JSON_PROPERTY_NOM,
  Materiel.JSON_PROPERTY_VALEUR_COMPTABLE,
  Materiel.JSON_PROPERTY_DEVISE,
  Materiel.JSON_PROPERTY_DATE_D_ACQUISITION,
  Materiel.JSON_PROPERTY_TAUX_DAPPRECIATION_ANNUEL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-29T12:58:40.550938700+01:00[GMT+01:00]", comments = "Generator version: 7.7.0")
public class Materiel implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_T = "t";
  private java.time.LocalDate t;

  public static final String JSON_PROPERTY_NOM = "nom";
  private String nom;

  public static final String JSON_PROPERTY_VALEUR_COMPTABLE = "valeur_comptable";
  private Integer valeurComptable;

  public static final String JSON_PROPERTY_DEVISE = "devise";
  private Devise devise;

  public static final String JSON_PROPERTY_DATE_D_ACQUISITION = "date_d_acquisition";
  private java.time.LocalDate dateDAcquisition;

  public static final String JSON_PROPERTY_TAUX_DAPPRECIATION_ANNUEL = "taux_dappreciation_annuel";
  private Double tauxDappreciationAnnuel;

  public Materiel() { 
  }

  public Materiel t(java.time.LocalDate t) {
    this.t = t;
    return this;
  }

  /**
   * Get t
   * @return t
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_T)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public java.time.LocalDate getT() {
    return t;
  }


  @JsonProperty(JSON_PROPERTY_T)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setT(java.time.LocalDate t) {
    this.t = t;
  }


  public Materiel nom(String nom) {
    this.nom = nom;
    return this;
  }

  /**
   * Get nom
   * @return nom
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getNom() {
    return nom;
  }


  @JsonProperty(JSON_PROPERTY_NOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNom(String nom) {
    this.nom = nom;
  }


  public Materiel valeurComptable(Integer valeurComptable) {
    this.valeurComptable = valeurComptable;
    return this;
  }

  /**
   * Get valeurComptable
   * @return valeurComptable
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALEUR_COMPTABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getValeurComptable() {
    return valeurComptable;
  }


  @JsonProperty(JSON_PROPERTY_VALEUR_COMPTABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValeurComptable(Integer valeurComptable) {
    this.valeurComptable = valeurComptable;
  }


  public Materiel devise(Devise devise) {
    this.devise = devise;
    return this;
  }

  /**
   * Get devise
   * @return devise
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEVISE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Devise getDevise() {
    return devise;
  }


  @JsonProperty(JSON_PROPERTY_DEVISE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDevise(Devise devise) {
    this.devise = devise;
  }


  public Materiel dateDAcquisition(java.time.LocalDate dateDAcquisition) {
    this.dateDAcquisition = dateDAcquisition;
    return this;
  }

  /**
   * Get dateDAcquisition
   * @return dateDAcquisition
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE_D_ACQUISITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public java.time.LocalDate getDateDAcquisition() {
    return dateDAcquisition;
  }


  @JsonProperty(JSON_PROPERTY_DATE_D_ACQUISITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateDAcquisition(java.time.LocalDate dateDAcquisition) {
    this.dateDAcquisition = dateDAcquisition;
  }


  public Materiel tauxDappreciationAnnuel(Double tauxDappreciationAnnuel) {
    this.tauxDappreciationAnnuel = tauxDappreciationAnnuel;
    return this;
  }

  /**
   * Get tauxDappreciationAnnuel
   * @return tauxDappreciationAnnuel
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAUX_DAPPRECIATION_ANNUEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getTauxDappreciationAnnuel() {
    return tauxDappreciationAnnuel;
  }


  @JsonProperty(JSON_PROPERTY_TAUX_DAPPRECIATION_ANNUEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTauxDappreciationAnnuel(Double tauxDappreciationAnnuel) {
    this.tauxDappreciationAnnuel = tauxDappreciationAnnuel;
  }


  /**
   * Return true if this Materiel object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Materiel materiel = (Materiel) o;
    return Objects.equals(this.t, materiel.t) &&
        Objects.equals(this.nom, materiel.nom) &&
        Objects.equals(this.valeurComptable, materiel.valeurComptable) &&
        Objects.equals(this.devise, materiel.devise) &&
        Objects.equals(this.dateDAcquisition, materiel.dateDAcquisition) &&
        Objects.equals(this.tauxDappreciationAnnuel, materiel.tauxDappreciationAnnuel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(t, nom, valeurComptable, devise, dateDAcquisition, tauxDappreciationAnnuel);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Materiel {\n");
    sb.append("    t: ").append(toIndentedString(t)).append("\n");
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("    valeurComptable: ").append(toIndentedString(valeurComptable)).append("\n");
    sb.append("    devise: ").append(toIndentedString(devise)).append("\n");
    sb.append("    dateDAcquisition: ").append(toIndentedString(dateDAcquisition)).append("\n");
    sb.append("    tauxDappreciationAnnuel: ").append(toIndentedString(tauxDappreciationAnnuel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `t` to the URL query string
    if (getT() != null) {
      joiner.add(String.format("%st%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getT()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `nom` to the URL query string
    if (getNom() != null) {
      joiner.add(String.format("%snom%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getNom()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `valeur_comptable` to the URL query string
    if (getValeurComptable() != null) {
      joiner.add(String.format("%svaleur_comptable%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getValeurComptable()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `devise` to the URL query string
    if (getDevise() != null) {
      joiner.add(getDevise().toUrlQueryString(prefix + "devise" + suffix));
    }

    // add `date_d_acquisition` to the URL query string
    if (getDateDAcquisition() != null) {
      joiner.add(String.format("%sdate_d_acquisition%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDateDAcquisition()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `taux_dappreciation_annuel` to the URL query string
    if (getTauxDappreciationAnnuel() != null) {
      joiner.add(String.format("%staux_dappreciation_annuel%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getTauxDappreciationAnnuel()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

