/*
 * harena
 * harena
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.harena.api.endpoint.rest.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.harena.api.endpoint.rest.model.Argent;
import com.harena.api.endpoint.rest.model.FluxArgent;
import com.harena.api.endpoint.rest.model.Materiel;
import java.util.Arrays;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.harena.api.endpoint.rest.client.ApiClient;
/**
 * PossessionAvecType
 */
@JsonPropertyOrder({
  PossessionAvecType.JSON_PROPERTY_TYPE,
  PossessionAvecType.JSON_PROPERTY_ARGENT,
  PossessionAvecType.JSON_PROPERTY_MATERIEL,
  PossessionAvecType.JSON_PROPERTY_FLUX_ARGENT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-29T12:58:40.550938700+01:00[GMT+01:00]", comments = "Generator version: 7.7.0")
public class PossessionAvecType implements Serializable {
  private static final long serialVersionUID = 1L;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    ARGENT("ARGENT"),
    
    MATERIEL("MATERIEL"),
    
    FLUXARGENT("FLUXARGENT");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  private TypeEnum type;

  public static final String JSON_PROPERTY_ARGENT = "argent";
  private Argent argent;

  public static final String JSON_PROPERTY_MATERIEL = "materiel";
  private Materiel materiel;

  public static final String JSON_PROPERTY_FLUX_ARGENT = "flux_argent";
  private FluxArgent fluxArgent;

  public PossessionAvecType() { 
  }

  public PossessionAvecType type(TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(TypeEnum type) {
    this.type = type;
  }


  public PossessionAvecType argent(Argent argent) {
    this.argent = argent;
    return this;
  }

  /**
   * Get argent
   * @return argent
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ARGENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Argent getArgent() {
    return argent;
  }


  @JsonProperty(JSON_PROPERTY_ARGENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArgent(Argent argent) {
    this.argent = argent;
  }


  public PossessionAvecType materiel(Materiel materiel) {
    this.materiel = materiel;
    return this;
  }

  /**
   * Get materiel
   * @return materiel
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MATERIEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Materiel getMateriel() {
    return materiel;
  }


  @JsonProperty(JSON_PROPERTY_MATERIEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMateriel(Materiel materiel) {
    this.materiel = materiel;
  }


  public PossessionAvecType fluxArgent(FluxArgent fluxArgent) {
    this.fluxArgent = fluxArgent;
    return this;
  }

  /**
   * Get fluxArgent
   * @return fluxArgent
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FLUX_ARGENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public FluxArgent getFluxArgent() {
    return fluxArgent;
  }


  @JsonProperty(JSON_PROPERTY_FLUX_ARGENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFluxArgent(FluxArgent fluxArgent) {
    this.fluxArgent = fluxArgent;
  }


  /**
   * Return true if this PossessionAvecType object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PossessionAvecType possessionAvecType = (PossessionAvecType) o;
    return Objects.equals(this.type, possessionAvecType.type) &&
        Objects.equals(this.argent, possessionAvecType.argent) &&
        Objects.equals(this.materiel, possessionAvecType.materiel) &&
        Objects.equals(this.fluxArgent, possessionAvecType.fluxArgent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, argent, materiel, fluxArgent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PossessionAvecType {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    argent: ").append(toIndentedString(argent)).append("\n");
    sb.append("    materiel: ").append(toIndentedString(materiel)).append("\n");
    sb.append("    fluxArgent: ").append(toIndentedString(fluxArgent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format("%stype%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getType()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `argent` to the URL query string
    if (getArgent() != null) {
      joiner.add(getArgent().toUrlQueryString(prefix + "argent" + suffix));
    }

    // add `materiel` to the URL query string
    if (getMateriel() != null) {
      joiner.add(getMateriel().toUrlQueryString(prefix + "materiel" + suffix));
    }

    // add `flux_argent` to the URL query string
    if (getFluxArgent() != null) {
      joiner.add(getFluxArgent().toUrlQueryString(prefix + "flux_argent" + suffix));
    }

    return joiner.toString();
  }
}

